fix: missing flags in Makefile and compatible changes to workflow
TJ-CSCCG/tongji-undergrad-thesis pull request #19
Opened 2022-12-20 05:52 UTC by CookiePieWw

2022-12-20 07:53 UTC, skyleaworlder commented
非常感谢！@CookiePieWw

既然进行了这方面的修改，我还有以下提议以完善本 PR：

* 可否以 `-xelatex` 作为 ENGINE 的默认选项。
* 修改 README.md 中有关 make 的部分，毕竟 ENGINE 的指定只在 Makefile 中，个人认为有必要增加如何指定 ENGINE 的说明。
* CI 原本都是使用 latexmk 统一编译三系统 pdf，目的之一是希望通过 test.yml 的指令让懂得一些 GitHub Actions 的同学能够一眼看出项目构建方式。（虽然我觉得不太会有人这么做就是了）目前转为使用 Makefile，我觉得可以把 windows 平台上的 latexmk 也换成使用 make.bat 的方式。

以上三点我认为可以考虑。直到 @CookiePieWw 表达对上述提议的看法前，本 PR 暂不合入。

2023-01-08 08:39 UTC, CookiePieWw commented
感谢 @skyleaworlder 的 review。

对 makefile 和 README.md 作了相应修改。对于 make.bat，由于我这里没有 win 的编译环境，因此只能尝试修改并使用 workflow 检查，不知道是什么原因，目前还无法成功生成 pdf 并上传。您对此有什么看法呢？

2023-01-08 08:51 UTC, skyleaworlder requested changes
或许应该是这里的问题，由于目前我也不是很方便，所以也很难测试。

不断尝试修复 CI 并使之通过的过程是非常痛苦的，我非常理解，真是麻烦同学了！

2023-01-08 08:51 UTC, skyleaworlder commented on make.bat
> +	latexmk %ENGINE% -synctex=1 -quiet -interaction=nonstopmode -file-line-error -halt-on-error -shell-escape %THESIS% 2>nul
原本的 CI 是通过：

```shell
latexmk ${{ matrix.compiler }} -interaction=nonstopmode -file-line-error -halt-on-error -shell-escape -jobname=windows${{ matrix.compiler }} main
```

也就是 `jobname` 指定了 latexmk 的输出 pdf 的名字。默认我记得应该是和输入一样的名字，所以应该在这里加上对名字的指定。

这里可以仿照外部传入 `ENGINE` 一样传入输出文件的名字，如果可以的话可以给一个默认值。

2023-01-08 09:39 UTC, CookiePieWw commented on make.bat
> +	latexmk %ENGINE% -synctex=1 -quiet -interaction=nonstopmode -file-line-error -halt-on-error -shell-escape %THESIS% 2>nul
之前 Linux 和 MacOS 上的做法是直接在 CI 里重命名然后上传，所以直接使用了这种方式，现在应该没什么大问题了。

（手忙脚乱地又提了个 PR，已经关闭了）

2023-01-08 12:03 UTC, skyleaworlder commented on make.bat
> +	latexmk %ENGINE% -synctex=1 -quiet -interaction=nonstopmode -file-line-error -halt-on-error -shell-escape %THESIS% 2>nul
哦哦是的，现在新的做法更正确，因为它将 make.bat 的功能与 CI 分开了。

2023-01-08 12:04 UTC, merged

2023-01-08 12:06 UTC, skyleaworlder commented
再次感谢 @CookiePieWw ！

修复 CI 在 GitHub Actions 上始终是一件痛苦的事情，感谢你对 `tongji-undergrad-thesis` 在多平台适配问题上所做出的努力。